---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: vagrant/keys/id_rsa
  children:
    yumserver:
      vars:
        centos_repo_path: /var/www/html/centos
        oel_repo_path: /var/www/html/oel
      hosts:
        devyumrepocentos:
          ansible_host: 192.168.5.10

    webservers:
      hosts:
        devcentos01:
          ansible_host: 192.168.5.20
    dbservers:
      hosts:
        devoel01:
          ansible_host: 192.168.5.30