---
# tasks file for httpd
- name: install httpd server
  yum:
    name: httpd
    state: latest

- name: install httpd server
  systemd:
    name: httpd
    state: stopped
  tags:
    - web-stop

- name: install httpd server
  systemd:
    name: httpd
    state: started
  tags:
    - web-start